name: Code analysis and tests

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
  analysis:
    name: checking code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: "16.17"
      - run: yarn
      - run: yarn lint
      - run: yarn test
